//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.26 at 09:06:05 PM IST 
//


package org.sonar.plugins.resharperplugin.objects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sonar.plugins.resharperplugin.objects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Element_QNAME = new QName("", "Element");
    private final static QName _Solution_QNAME = new QName("", "Solution");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sonar.plugins.resharperplugin.objects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.IssueTypes }
     * 
     */
    public IssueTypes createIssueTypes() {
        return new IssueTypes();
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.IssueType }
     * 
     */
    public IssueType createIssueType() {
        return new IssueType();
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.Issue }
     * 
     */
    public Issue createIssue() {
        return new Issue();
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.Information }
     * 
     */
    public Information createInformation() {
        return new Information();
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.InspectionScope }
     * 
     */
    public InspectionScope createInspectionScope() {
        return new InspectionScope();
    }

    /**
     * Create an instance of {@link org.sonar.plugins.resharperplugin.objects.Issues }
     * 
     */
    public Issues createIssues() {
        return new Issues();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Element")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createElement(String value) {
        return new JAXBElement<String>(_Element_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Solution")
    public JAXBElement<String> createSolution(String value) {
        return new JAXBElement<String>(_Solution_QNAME, String.class, null, value);
    }

}
